[package]
name = "sdx_art"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18"
sdx_art_lib = { path = "../sdx_art_lib" }
